export {default as AcoountIcon}  from './Account'
export { default as Apps } from './Apps'
export { default as Bell } from './Bell'
export { default as PhotosIcon } from './CameraIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as GroupIconFilled } from './GroupFilledIcon'
export { default as HomeFilledIcon } from './HomeIconFiled'
export { default as HomeOutlineIcon } from './HomeIconOutline'
export { default as MessangerIcon } from './MessangerIcon'
export { default as PeopleFilledIcons } from './PeopleFilled'
export { default as PeopleOutlineIcon } from './PeopleIconOutline'
export { default as SmileIcon } from './SmileFaceIcon'
export { default as UserGroupOutline } from './UserGroupOutline'

export { default as VideoameraIcon } from './VideoCameraIcon'